services:
  postgresql:
    image: postgres:17.4-alpine
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: cryptellation_exchanges
    networks:
      - cryptellation-exchanges

  temporal:
    depends_on:
      - postgresql
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
    image: temporalio/auto-setup:1.25
    ports:
      - 7233:7233
    expose:
      - 7233
    volumes:
      - ./temporal:/etc/temporal/config/dynamicconfig
    networks:
      - cryptellation-exchanges
  temporal-ui:
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    image: temporalio/ui:2.31.2
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      - cryptellation-exchanges

  migrator:
    depends_on:
      - postgresql
    image: golang:1.23.8-alpine
    command: ["go", "run", "./cmd/worker", "database", "migrate"]
    working_dir: /go/src/github.com/cryptellation/exchanges
    environment:
      SQL_DSN: "host=postgresql user=cryptellation_exchanges password=cryptellation_exchanges dbname=cryptellation_exchanges sslmode=disable"
    volumes:
      - gocache:/go/pkg/mod
      - gobuild:/root/.cache/go-build
      - .:/go/src/github.com/cryptellation/exchanges
    networks:
      - cryptellation-exchanges

volumes:
  gocache:
  gobuild:

networks:
  cryptellation-exchanges:
